<ul>
	<li><a href="index.php">Inicio</a></li>
	<li><a>Usuarios</a>
		<ul>
			<li><a href="formularioregistro.php">Agregar Usuario</a></li>
			<li><a href="ver_user.php">Ver Usuario</a></li>
		</ul>
	</li>
	<li><a>Colegios</a>
		<ul>
			<li><a href="formulariocolegios.php">Agregar Colegio</a></li>
			<li><a href="ver_colegioadministrador.php">Ver Colegio</a></li>
		</ul>
	</li>
	</li>
	<li><a>Reportes</a>
		<ul>
			<li><a href="reporte.php">Generar reporte</a></li>
			
		</ul>
	</li>
	<li><a>Copia de seguridad</a>
		<ul>
			<li><a href="php/backup.php">Generar copia</a></li>
		</ul>
	</li>
</ul>

</div>

</nav>