<ul>
	<li><a href="index.php">Inicio</a></li>
	<li><a>Usuarios</a>
		<ul>
			<li><a href="ver_user.php">Ver Usuario</a></li>
		</ul>
	</li>
	<li><a>Prefil del Colegios</a>
		<ul>
			<li><a href="ver_colegioadmin.php">Ver Colegio</a></li>
		</ul>
	</li>
	<li><a>Grados</a>
		<ul>
			<li><a href="formulariogrado.php">Agregar grados</a></li>
		</ul>
	
	</li>
	<li><a>Cupos</a>
		<ul>
			<li><a href="ver_cupo.php">Ver cupos</a></li>
		</ul>
	
	</li>
</ul>
</div>
</center>
</nav>